### ISSUE TITLE
Package won't build

### ISSUE THREAD

**Issue by skorokithakis** [ditashi/jsbeautifier-go#2]
I can't get this to work. `go get` gives me:

```
package jsbeautifier/jsbeautifier: unrecognized import path "jsbeautifier/jsbeautifier"
```

**Comment by ditashi** [comment]
You're right, this is my first Go project GitHub, I have correctly set the paths now and it should work :)

**Comment by skorokithakis** [comment]
Thanks, that's what I did locally too and it worked :) I tried running it and it won't indent, though, I'm not sure if I did something wrong or if it's the program's fault. Everything just had 0 leading whitespace.

**Comment by ditashi** [comment]
Could you provide me with the sample ?

**Comment by skorokithakis** [comment]
Sure: https://raw.githubusercontent.com/skorokithakis/msgpgen/master/chrome/msgpgen/content/contentScript.js

**Comment by ditashi** [comment]
Thanks, I'm looking into it #3
